///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PracticeRegressionTest.Regression.App1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validation recording.
    /// </summary>
    [TestModule("5ad94ffd-e716-4fdf-84da-633f7ebb5a94", ModuleType.Recording, 1)]
    public partial class Validation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PracticeRegressionTest.PracticeRegressionTestRepository repository.
        /// </summary>
        public static global::PracticeRegressionTest.PracticeRegressionTestRepository repo = global::PracticeRegressionTest.PracticeRegressionTestRepository.Instance;

        static Validation instance = new Validation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(0));
            Delay.Duration(2000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ApplicationUnderTest.Self, false, new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Tapper, Jake') on item 'ApplicationUnderTest.TapperJake'.", repo.ApplicationUnderTest.TapperJakeInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.TapperJakeInfo, "InnerText", "Tapper, Jake");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UcTopNavigationLbtnLogout' at Center.", repo.ApplicationUnderTest.UcTopNavigationLbtnLogoutInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.UcTopNavigationLbtnLogout.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
