///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PracticeRegressionTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PracticeRegressionTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3b5b03a9-687b-4b12-a379-fe338a2a6d19")]
    public partial class PracticeRegressionTestRepository : RepoGenBaseFolder
    {
        static PracticeRegressionTestRepository instance = new PracticeRegressionTestRepository();
        PracticeRegressionTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the PracticeRegressionTestRepository element repository.
        /// </summary>
        [RepositoryFolder("3b5b03a9-687b-4b12-a379-fe338a2a6d19")]
        public static PracticeRegressionTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PracticeRegressionTestRepository() 
            : base("PracticeRegressionTestRepository", "/", null, 0, false, "3b5b03a9-687b-4b12-a379-fe338a2a6d19", ".\\RepositoryImages\\PracticeRegressionTestRepository3b5b03a9.rximgres")
        {
            _applicationundertest = new PracticeRegressionTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

        string _NewVariable = "btnSubmit";

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("dab575a2-4e64-4fd5-a3ce-96d126c60ea4")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3b5b03a9-687b-4b12-a379-fe338a2a6d19")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("dd4dc026-3133-49a2-b45a-45cbc1883825")]
        public virtual PracticeRegressionTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PracticeRegressionTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("dd4dc026-3133-49a2-b45a-45cbc1883825")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tbxusernameInfo;
            RepoItemInfo _tbxpasswordInfo;
            RepoItemInfo _btnsubmitInfo;
            RepoItemInfo _lnkpatientsInfo;
            RepoItemInfo _tbxpatientsearchInfo;
            RepoItemInfo _btnpatientsearchInfo;
            RepoItemInfo _tapperjakeInfo;
            RepoItemInfo _patientsearchInfo;
            RepoItemInfo _uctopnavigationlbtnlogoutInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='prodtest.enclarapharmacia.com']", parentFolder, 30000, null, false, "dd4dc026-3133-49a2-b45a-45cbc1883825", "")
            {
                _tbxusernameInfo = new RepoItemInfo(this, "TbxUserName", ".//input[#'tbxUserName']", 30000, null, "d327b3f3-902c-456d-8e8f-1e84e20855cb");
                _tbxpasswordInfo = new RepoItemInfo(this, "TbxPassword", ".//input[#'tbxPassword']", 30000, null, "f4691b86-2861-44b5-8816-7105919b2c69");
                _btnsubmitInfo = new RepoItemInfo(this, "BtnSubmit", ".//input[#$NewVariable]", 30000, null, "2e02ed2c-dd0e-47eb-b890-840526b9d2f2");
                _lnkpatientsInfo = new RepoItemInfo(this, "LnkPatients", ".//a[#'lnkPatients']", 30000, null, "8bbbc31b-9342-4eb1-8853-2c2f30d82c5b");
                _tbxpatientsearchInfo = new RepoItemInfo(this, "TbxPatientSearch", ".//input[#'tbxPatientSearch']", 30000, null, "370fac0f-11d7-41a2-b23a-b4c7c9ded312");
                _btnpatientsearchInfo = new RepoItemInfo(this, "BtnPatientSearch", ".//input[#'btnPatientSearch']", 30000, null, "bd335884-ce3a-400b-b959-aea694256768");
                _tapperjakeInfo = new RepoItemInfo(this, "TapperJake", ".//table[#'grvPatient']/tbody/tr[2]/td[2]/table/?/?/tr/td[1]/?/?/b[@innertext='Tapper, Jake']", 30000, null, "bcceddc5-e429-433b-8044-85386759e4a2");
                _patientsearchInfo = new RepoItemInfo(this, "PatientSearch", ".//li[#'liPatSearch']/a[@innertext='Patient Search']", 30000, null, "ca5c4c85-c3cf-44dc-aed9-85b646086e53");
                _uctopnavigationlbtnlogoutInfo = new RepoItemInfo(this, "UcTopNavigationLbtnLogout", ".//a[#'ucTopNavigation_lbtnLogout']", 30000, null, "e4682e05-5dc1-4c09-9e3c-886d5ba17f55");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dd4dc026-3133-49a2-b45a-45cbc1883825")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dd4dc026-3133-49a2-b45a-45cbc1883825")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TbxUserName item.
            /// </summary>
            [RepositoryItem("d327b3f3-902c-456d-8e8f-1e84e20855cb")]
            public virtual Ranorex.InputTag TbxUserName
            {
                get
                {
                    return _tbxusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TbxUserName item info.
            /// </summary>
            [RepositoryItemInfo("d327b3f3-902c-456d-8e8f-1e84e20855cb")]
            public virtual RepoItemInfo TbxUserNameInfo
            {
                get
                {
                    return _tbxusernameInfo;
                }
            }

            /// <summary>
            /// The TbxPassword item.
            /// </summary>
            [RepositoryItem("f4691b86-2861-44b5-8816-7105919b2c69")]
            public virtual Ranorex.InputTag TbxPassword
            {
                get
                {
                    return _tbxpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TbxPassword item info.
            /// </summary>
            [RepositoryItemInfo("f4691b86-2861-44b5-8816-7105919b2c69")]
            public virtual RepoItemInfo TbxPasswordInfo
            {
                get
                {
                    return _tbxpasswordInfo;
                }
            }

            /// <summary>
            /// The BtnSubmit item.
            /// </summary>
            [RepositoryItem("2e02ed2c-dd0e-47eb-b890-840526b9d2f2")]
            public virtual Ranorex.InputTag BtnSubmit
            {
                get
                {
                    return _btnsubmitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BtnSubmit item info.
            /// </summary>
            [RepositoryItemInfo("2e02ed2c-dd0e-47eb-b890-840526b9d2f2")]
            public virtual RepoItemInfo BtnSubmitInfo
            {
                get
                {
                    return _btnsubmitInfo;
                }
            }

            /// <summary>
            /// The LnkPatients item.
            /// </summary>
            [RepositoryItem("8bbbc31b-9342-4eb1-8853-2c2f30d82c5b")]
            public virtual Ranorex.ATag LnkPatients
            {
                get
                {
                    return _lnkpatientsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LnkPatients item info.
            /// </summary>
            [RepositoryItemInfo("8bbbc31b-9342-4eb1-8853-2c2f30d82c5b")]
            public virtual RepoItemInfo LnkPatientsInfo
            {
                get
                {
                    return _lnkpatientsInfo;
                }
            }

            /// <summary>
            /// The TbxPatientSearch item.
            /// </summary>
            [RepositoryItem("370fac0f-11d7-41a2-b23a-b4c7c9ded312")]
            public virtual Ranorex.InputTag TbxPatientSearch
            {
                get
                {
                    return _tbxpatientsearchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TbxPatientSearch item info.
            /// </summary>
            [RepositoryItemInfo("370fac0f-11d7-41a2-b23a-b4c7c9ded312")]
            public virtual RepoItemInfo TbxPatientSearchInfo
            {
                get
                {
                    return _tbxpatientsearchInfo;
                }
            }

            /// <summary>
            /// The BtnPatientSearch item.
            /// </summary>
            [RepositoryItem("bd335884-ce3a-400b-b959-aea694256768")]
            public virtual Ranorex.InputTag BtnPatientSearch
            {
                get
                {
                    return _btnpatientsearchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BtnPatientSearch item info.
            /// </summary>
            [RepositoryItemInfo("bd335884-ce3a-400b-b959-aea694256768")]
            public virtual RepoItemInfo BtnPatientSearchInfo
            {
                get
                {
                    return _btnpatientsearchInfo;
                }
            }

            /// <summary>
            /// The TapperJake item.
            /// </summary>
            [RepositoryItem("bcceddc5-e429-433b-8044-85386759e4a2")]
            public virtual Ranorex.BTag TapperJake
            {
                get
                {
                    return _tapperjakeInfo.CreateAdapter<Ranorex.BTag>(true);
                }
            }

            /// <summary>
            /// The TapperJake item info.
            /// </summary>
            [RepositoryItemInfo("bcceddc5-e429-433b-8044-85386759e4a2")]
            public virtual RepoItemInfo TapperJakeInfo
            {
                get
                {
                    return _tapperjakeInfo;
                }
            }

            /// <summary>
            /// The PatientSearch item.
            /// </summary>
            [RepositoryItem("ca5c4c85-c3cf-44dc-aed9-85b646086e53")]
            public virtual Ranorex.ATag PatientSearch
            {
                get
                {
                    return _patientsearchInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The PatientSearch item info.
            /// </summary>
            [RepositoryItemInfo("ca5c4c85-c3cf-44dc-aed9-85b646086e53")]
            public virtual RepoItemInfo PatientSearchInfo
            {
                get
                {
                    return _patientsearchInfo;
                }
            }

            /// <summary>
            /// The UcTopNavigationLbtnLogout item.
            /// </summary>
            [RepositoryItem("e4682e05-5dc1-4c09-9e3c-886d5ba17f55")]
            public virtual Ranorex.ATag UcTopNavigationLbtnLogout
            {
                get
                {
                    return _uctopnavigationlbtnlogoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The UcTopNavigationLbtnLogout item info.
            /// </summary>
            [RepositoryItemInfo("e4682e05-5dc1-4c09-9e3c-886d5ba17f55")]
            public virtual RepoItemInfo UcTopNavigationLbtnLogoutInfo
            {
                get
                {
                    return _uctopnavigationlbtnlogoutInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
